# SPDX-FileCopyrightText: 2025 Chimera-NAS Project Contributors
#
# SPDX-License-Identifier: Unlicense

title: chimera
description: chimera documentation
theme: just-the-docs
color_scheme: dark


url: https://chimeraproject.io/chimera

aux_links:
  GitHub: https://github.com/chimera-nas/chimera

