# SPDX-FileCopyrightText: 2025 Chimera-NAS Project Contributors
#
# SPDX-License-Identifier: Unlicense

name: Syntax Check

on:
  pull_request:
  workflow_dispatch:   # allow manual runs

jobs:
  syntax-check:
    name: Check code formatting with uncrustify
    runs-on: arc-amd64
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Configure APT mirror
        run: |
          if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then
            sudo sed -i 's|http://archive.ubuntu.com/ubuntu|http://repository.mdh.quantum.com/repository/pkgs/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources
            sudo sed -i 's|http://security.ubuntu.com/ubuntu|http://repository.mdh.quantum.com/repository/pkgs/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources
          else
            sudo sed -i 's|http://archive.ubuntu.com/ubuntu|http://repository.mdh.quantum.com/repository/pkgs/ubuntu|g' /etc/apt/sources.list
            sudo sed -i 's|http://security.ubuntu.com/ubuntu|http://repository.mdh.quantum.com/repository/pkgs/ubuntu|g' /etc/apt/sources.list
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y uncrustify make
      
      - name: Run syntax check
        run: make syntax-check